add a check to see if mysql is installed

diff --git a/pantheon-db-cli b/pantheon-db-cli
--- a/pantheon-db-cli
+++ b/pantheon-db-cli
@@ -2,6 +2,13 @@
 # pantheon-db-cli
 # Get a MySQL commandline on a Pantheon server that requires an SSH tunnel.
 
+# check if command exists and fail otherwise
+command -v mysql >/dev/null 2>&1
+  if [[ $? -ne 0 ]]; then
+    echo "mysql is not installed."
+      exit 1
+  fi
+
 if [[ $# -lt 2 ]] ; then
 >&2  echo -e 'Usage:'
 >&2  echo -e "  $(basename $0) [site] [environment]"
